### ISSUE TITLE
Node.js stable points to 0.10.35, unstable to 0.12.0

### ISSUE THREAD

**Issue by piranna** [heroku/semver.io#31]
Node.js stable now it's v0.12.0, but it's shown as [unstable](https://semver.io/node/unstable) while at the same time the [stable](https://semver.io/node/stable) one is set to v0.10.35. I think stable should point to 0.12.0and unstable to 0.11.16 or at least to 0.12.0, too.

**Comment by hunterloftis** [comment]
We limit the maximum version (`MAX_STABLE_VERSION`) to prevent automatic updates from breaking deploys. Once we have tested a version, we bump the max stable version... we're currently updating our test suite to use Docker, so this has taken a little longer than usual, but we'll bump this to 0.12 this week.

Thanks!

**Comment by piranna** [comment]
Oh, ok, thank you! :-)

2015-02-16 20:17 GMT+01:00 Hunter Loftis <notifications@github.com>:

> We limit the maximum version (MAX_STABLE_VERSION) to prevent automatic
> updates from breaking deploys. Once we have tested a version, we bump the
> max stable version... we're currently updating our test suite to use
> Docker, so this has taken a little longer than usual, but we'll bump this
> to 0.12 this week.
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/heroku/semver.io/issues/31#issuecomment-74558813>.
>



-- 
"Si quieres viajar alrededor del mundo y ser invitado a hablar en un monton
de sitios diferentes, simplemente escribe un sistema operativo Unix."
– Linus Tordvals, creador del sistema operativo Linux

**Comment by hunterloftis** [comment]
Updated! http://semver.io/node

:party:

**Comment by piranna** [comment]
Cool! :-)

**Comment by icflorescu** [comment]
Still a bit behind, though ;-). According to the [official blog post](http://blog.nodejs.org/), 0.12.2 is the last stable version now, while semver.io still points to 0.12.0.
