### ISSUE TITLE
stable incorrectly omits some versions

### ISSUE THREAD

**Issue by mzgol** [heroku/semver.io#34]
The [IoJsSource.prototype._parse](https://github.com/heroku/semver.io/blob/aba71a822fdbdf69e3e7e4f2d1792bc49fd95cad/lib/sources/iojs.js#L39-L49) function incorrectly assumes that a non-even minor means the version is unstable. This was only a valid convention for Node.js, it was never valid for io.js. All io.js versions are considered final & stable. io.js follows semver.

In particular, this incorrectly marks io.js 2.1.0 as unstable.

The logic should be removed in the io.js case.

**Comment by hunterloftis** [comment]
Sounds good, PRs welcome!

**Comment by mzgol** [comment]
@hunterloftis PR submitted: #36.

**Comment by mzgol** [comment]
@hunterloftis A kindle reminder about my PR. :-)

**Comment by mzgol** [comment]
@hunterloftis Is there anything blocking my PR?
