### ISSUE TITLE
Not updating to latest node

### ISSUE THREAD

**Issue by matthew-andrews** [heroku/semver.io#37]
New version of node released with critical security update ~18h ago:-
https://twitter.com/nodejs/status/617163261901844480

But not yet appearing on semver.io:-
https://semver.io/node/resolve?range=undefined
(returns v0.12.5)

It looks like the URL used for updates has the version on it:-
https://github.com/heroku/semver.io/blob/aba71a822fdbdf69e3e7e4f2d1792bc49fd95cad/lib/sources/node.js#L14

http://nodejs.org/dist/

Maybe the dyno just needs restarting?

**Comment by hunterloftis** [comment]
Bumped `MAX_STABLE_NODE`, should be all set.

**Comment by matthew-andrews** [comment]
thank you !
