### ISSUE TITLE
Node 4.0.0-rc.1 not detected

### ISSUE THREAD

**Issue by mgol** [heroku/semver.io#42]
Node.js >=4 pre-releases are kept in different directories than the release ones. For example Node.js 4.0.0-rc.1 is kept under https://nodejs.org/download/rc/. This makes http://semver.io/node.json not detect it and still claim 0.12.7 is the latest version, including unstable ones.

**Comment by mzgol** [comment]
It seems the currently used http://nodejs.org/dist/ is mostly kept as legacy, everything is under https://nodejs.org/download/release/ now. Also, note that the latter URL is https-only.

**Comment by Binarytales** [comment]
I've created a pull request that aims to resolve this issue https://github.com/heroku/semver.io/pull/43

**Comment by hunterloftis** [comment]
Closing stale issues, please ping me to reopen if this is still a problem.

**Comment by mgol** [comment]
This is still an issue. There's no support for pre-releases of Node.js 4 & newer in semver.io.

**Comment by hunterloftis** [comment]
Any thoughts on an API change that would make sense for exposing pre-releases?

**Comment by mgol** [comment]
The current way of getting the Node version list is not ideal: it downloads the legacy https://nodejs.org/dist/ page, parses the HTML and converts it to a list - way too hacky. A proper solution would be to change that to reading https://nodejs.org/download/release/index.json and getting the list out of it (filtering out unstable versions as they are still there for Node.js 0.x). Unstable versions should then be composed from the filtered ones in https://nodejs.org/download/release/index.json and all entries in https://nodejs.org/download/rc/index.json. If betas get their home in the future (I don't see anything beta-related at https://nodejs.org/download/ and I don't think supporting nightlies is needed) this would just be a question of reading one more file.

As for the semver.io side of things, I'd expect https://semver.io/node.json to return all the version in the `all` field and the latest of them in the `unstable` field.

**Comment by edmorley** [comment]
This project + the semver.io site which runs it has been deprecated for some time, and due to be switched off soon - so it should no longer be used.
