### ISSUE TITLE
Node 4.0.0 is out

### ISSUE THREAD

**Issue by mzgol** [heroku/semver.io#44]
I assume it doesn't show up under https://semver.io/node.json as stable as you accept each release manually? Otherwise 4.0.0 should be recognized as stable.

**Comment by hunterloftis** [comment]
Yep, the release is there (http://semver.io/node/versions) but we test each release a bit before bumping the `MAX_STABLE_NODE` version. In this case, I'll probably have to hold off on bumping the default until post-Dreamforce.

**Comment by mzgol** [comment]
OK, thanks. :) What's Dreamforce and when may it happen?

-- 
Michał Gołębiowski

**Comment by hunterloftis** [comment]
It's Salesforce's huge conference in SF next week: http://www.salesforce.com/dreamforce/DF15/

We're super conservative about releases just before DF since there are demos happening 24/7.

If you'd like to use 4.0.0 though, you can right now (just have to specify it in engines.node).

**Comment by mzgol** [comment]
> If you'd like to use 4.0.0 though, you can right now (just have to specify it in engines.node).

Great, thanks!

**Comment by silverwind** [comment]
Looking forward to this bump!

**Comment by matthew-andrews** [comment]
Now Dreamforce is over can we expect to see this soon? :smile:

**Comment by hunterloftis** [comment]
Yep, default has been bumped to 4.1.1.

Keep in mind, waiting on the defaults to update is not the best strategy. It's much better to specify the runtime your app uses in engines.node (in package.json). Having a 'floating' production runtime version is dangerous.

**Comment by silverwind** [comment]
@hunterloftis indeed a fixed version is probably what most critical apps want.

In my case, I support `>0.10.0` and the app isn't really critical. I still like to experience breakage in new node versions as soon as possible so I can fix them, thought.

This double usage of the engine.node for both deployment and compatibilty declaration isn't really optimal in my case. I sometimes wish there would be a seperate field for the deployment version.
