### ISSUE TITLE
How to handle pre-release and LTS versions of Node post v4.0.0

### ISSUE THREAD

**Issue by Binarytales** [heroku/semver.io#49]
The Node.js and io.js projects have merged and had their first unified release: Node 4.0.0

In October 2015 the Node Foundation will take a snapshot of the then stable version of v4 (eg. 4.1.7) which will become the first LTS (Long Term Support) version of Node with support until April 2017. At the same time a pre-release version Node 5.0.0 will be made available.

This issue is here to track suggestion for how semver.io will handle pre-release and LTS versions of Node post v4.0.0 now that Node has moved away from it's linux style odd:unstable::even:stable versioning system and is now SemVer compliant.

**Comment by Binarytales** [comment]
Some relevant issues and documentation from the Node project:

https://github.com/nodejs/dev-policy#release-process-and-branching-model
nodejs/node#2522
https://github.com/nodejs/LTS

**Comment by hunterloftis** [comment]
semver.io still just deals with semantic versioning; working on higher level abstractions for things like LTS (https://nodebin.herokuapp.com/)
