### ISSUE TITLE
Versions in README are out of date

### ISSUE THREAD

**Issue by zeke** [heroku/semver.io#50]
Are these updated manually now? If so, I can submit a PR with latest results.

``` sh
curl https://semver.io/node/stable
0.10.33

curl https://semver.io/node/unstable
0.11.14

curl https://semver.io/node/resolve/0.8.x
0.8.28

curl https://semver.io/nginx/stable
1.6.2
```

**Comment by hunterloftis** [comment]
Works for me! If you prefer a generator to periodically bump the readme versions, we can do that too.

**Comment by edmorley** [comment]
This project + the semver.io site which runs it has been deprecated for some time, and due to be switched off soon - so it should no longer be used.
