### ISSUE TITLE
Provide optional list of versions to match against

### ISSUE THREAD

**Issue by jasonkarns** [heroku/semver.io#51]
This is a great tool and is quite helpful for the nodenv ecosystem. @hurrymaplelad built a [plugin for nodenv](https://github.com/hurrymaplelad/nodenv-package-json-engine) that lets nodenv pull its version from package.json `engines` instead of `.node-version`. It is using this service to determine the best node version that satisfies the version spec from `engines`. However, that's only half the puzzle for nodenv. In addition to simply finding the maximum version match for a given semver range, we would like to take into account versions that are installed.

I would love to see the ability to pass a semver range and also a list of versions, and have semver.io select the best option available from the provided list (defaulting to current behavior if none match).

Since this would be an optional extra parameter (array), then omitting it does not alter current behavior.

Example:

```
https://semver.io/node/resolve?range=>%3D4.0.0
5.0.0

https://semver.io/node/resolve?range=>%3D4.0.0&v=4.2.1
4.2.1

https://semver.io/node/resolve?range=>%3D4.0.0&v=4.0.0&v=4.1.0&v=4.2.1
4.2.1

https://semver.io/node/resolve?range=>%3D4.0.0&v=0.10.0&v=0.12.0
5.0.0
```

Thoughts?

**Comment by hurrymaplelad** [comment]
Cool idea Jason! I wonder if we can compare installed versions against a semver expression locally to avoid the network dependency for the common case?  I bet there's a nose module that does this. Haven't looked yet

**Comment by hunterloftis** [comment]
This is certainly possible, but I'm not sure if it's something you'd want to do on a web service vs just a local match. It would be pretty trivial for instance to pull down [semver.io/node/versions](http://semver.io/node/versions) and then determine that `matchingVersions = _.intersection(allVersions, localVersions)`.

**Comment by hurrymaplelad** [comment]
@hunterloftis thanks for the pointers.  It seems like `matchingVersions = _.intersection(allVersions, localVersions)` would tell us if the local version is a legit node version.  Any suggestions for comparing a list of local versions against a range expression like `~1.3` ?

**Comment by zeke** [comment]
@hurrymaplelad I think `semver.maxSatisfying` is what you need:

> maxSatisfying(versions, range): Return the highest version in the list that satisfies the range, or null if none of them do.

Here's how semver.io does it: https://github.com/heroku/semver.io/blob/208828269ab0839e56a2bcb7b83232a2a32390f9/lib/resolver.js#L64-L70

**Comment by hurrymaplelad** [comment]
@zeke perfect, thanks!  Now I just need a native or shell script implementation to bootstrap node...

**Comment by jasonkarns** [comment]
I'd imagine that you could code the plugin in node as long as it didn't use
any non core modules. Since (within the context of the plugin) we know at
least /a/ node is installed, we just don't know which to select. So if this
is coded such that it works on /any/ node (and without an npm install),
you'd be safe.

But that's a lot of restrictions and may be simpler to just stay in shell.

Though this does make me wonder if we could add a desire to nodenv itself
that would allow plugins to run in a particular node

**Comment by zeke** [comment]
@hurrymaplelad if you want to bootstrap node, here's how the heroku buildpack does it: https://github.com/heroku/heroku-buildpack-nodejs/blob/67291e8c9afa15720219652e490d34d9d28735a6/lib/binaries.sh#L45-L62
