### ISSUE TITLE
node.js stable version is wrong

### ISSUE THREAD

**Issue by pwnall** [heroku/semver.io#54]
The latest release is 5.3.0, semver.io reports 5.1.1.

FWIW, processing https://nodejs.org/dist/index.json might be easier and more robust than scraping https://nodejs.org/dist/

**Comment by hunterloftis** [comment]
Great suggestion to use the JSON index, I didn't know it existed.

Stable version will always lag behind; we manually test before bumping all customer defaults up. This will change soon with an update to have semver.io mirror the LTS vs stable pattern node recently adopted.

**Comment by zeke** [comment]
Wow. Nice that https://nodejs.org/dist/index.json exists now.

**Comment by ChrisAntaki** [comment]
> This will change soon with an update to have semver.io mirror the LTS vs stable pattern node recently adopted.

Sweet! Is there an ETA on this update?
