### ISSUE TITLE
https://semver.io/node/resolve/5.10.x returns incorrect result

### ISSUE THREAD

**Issue by emkman** [heroku/semver.io#55]
**https://semver.io/node/resolve/5.10.x** returns the incorrect result, returning `5.10.0`. The latest released version matching this range is `5.10.1` so I presume the result should either be

```
5.10.0
5.10.1
```

if it is meant to show all matches, or

```
5.10.1
```

if it is meant to return the latest version. The `node-semver` command line behaves as expected

```
[emkman@Ethans-MacBook-Pro  ~]$ semver 5.10.0 5.10.1 -r 5.10.x
5.10.0
5.10.1
```

**Comment by emkman** [comment]
Looking at the source, it appears versions are pulled from https://nodejs.org/dist/ which does indeed contain a **v5.10.1/** folder. Are these results cached and if so, how often are these updated?

**Comment by zeke** [comment]
If I remember correctly, the results are cached in memory at app startup. Dynos are restarted automatically at least once every 24 hours.

**Comment by emkman** [comment]
OK than this is definitely a bug, as the 5.10.1 release is at least a week old at this point.

**Comment by zeke** [comment]
There's also an environment variable that allows Heroku employees to conservatively control the max latest version: https://github.com/heroku/semver.io/blob/5ea90dbb4cf4022da456d83afb6f194ae6abb6bb/lib/app.js#L21

This exists as a protection to users because there are often issues with releases when the first come out. 

If you want to bypass it, specify an exact version string for `engines.node` in your package.json file.

**Comment by emkman** [comment]
Gotcha, couldn't tell that from the website or the docs.

**Comment by zeke** [comment]
> couldn't tell that from the website or the docs.

Good call. Want to submit a PR?

**Comment by emkman** [comment]
My impression was that the site was a public service for general use that was used/supported/sponsored/hosted by Heroku as well. Since they are controlling the version ranges as they relate to Heroku deployments, I think they would be the best people to dictate the copy on the website as well.

**Comment by hunterloftis** [comment]
We're working on removing those limits from semver (and adding them at another step in the build process so we don't have to tie the semver service to Heroku's node build needs).

**Comment by emkman** [comment]
Sounds great, thanks for the update.

**Comment by mgol** [comment]
This particular issue has been fixed.
