### ISSUE TITLE
latest node is 6.5.0. ">= 4" resolves to 5.11.1

### ISSUE THREAD

**Issue by tjwebb** [heroku/semver.io#57]
https://semver.io/node/resolve/%3E=4

`engines.node` of `>= 4` should resolve to the latest version of node, which is 6.5.0, not 5.11. yes? I think 5.x series is nearly EOL already.

If I am wrong, then I'd appreciate any insight on how to write "the largest version number and also greater than 4.0". thanks

**Comment by mscdex** [comment]
It looks like the node module is scraping the https://nodejs.org/dist listing instead of parsing the more appropriate https://nodejs.org/dist/index.json or https://nodejs.org/dist/index.tab

**Comment by mgol** [comment]
@mscdex That's true (I adapted the existing code when I was adding support for newer Nodes) but it shouldn't affect this issue, all the files are still there.

The stable version is updated manually so one of the maintainers needs to bump it; see https://github.com/heroku/semver.io/issues/44#issuecomment-138689865.

**Comment by mgol** [comment]
@hunterloftis could you have a look? Node 5 has been EOL'd for some time so defaulting to it is dangerous.

**Comment by Lomand** [comment]
Is there any news regarding this issue?

**Comment by mgol** [comment]
This has been fixed. @tjwebb you can close the issue.

**Comment by hunterloftis** [comment]
resolved by https://github.com/heroku/semver.io/pull/63
