### ISSUE TITLE
https://semver.io/node/resolve/>=6 returns 6.9.1

### ISSUE THREAD

**Issue by quarterto** [heroku/semver.io#62]
Should currently be `7.4.0`. `^6.0.0` is also returning `6.9.1` but it should be `6.9.3`.

Similar to #57 but that's apparently fixed.

**Comment by JordanBelford** [comment]
If I understand correctly, the stable version is maintained manually, and it also currently resolves to 6.9.1. 
Is the latest stable an upper bound on the version that is resolved in an expression like ^6.0.0?

**Comment by JordanBelford** [comment]
Resolver.prototype.satisfy in lib/resolver.js has the answer here.

The logic first tries to find a stable version to satisfy the semver expression, which is upper bound by the MAX_STABLE_NODE environment variable. If none is found, it tries to find a match using all available versions, including those greater than MAX_STABLE_NODE. If it still fails it just returns the version in MAX_STABLE_NODE.

Example with MAX_STABLE_NODE = 6.9.1 and actual latest 6.x = 6.9.4
^6.0.0 => 6.9.1
^6.9.2 => 6.9.4
^999.9.9 => 6.9.1

Does it make sense to require manual updating of the stable version? I'm curious about the history there.

**Comment by JordanBelford** [comment]
Looks like the update mentioned in #54 is going to take care of this.

**Comment by hunterloftis** [comment]
resolved by https://github.com/heroku/semver.io/pull/63
