### ISSUE TITLE
document support for query params

### ISSUE THREAD

**Issue by zeke** [heroku/semver.io#66]
Hi @jmorrell !!!

I want to open a PR documenting support for the `range` query param:

```
$ curl "https://semver.io/node/resolve/?range=^8.3.0"
8.11.1
```

Before I do so, just want to make sure it's wanted, and that it has a chance of being merged :)

**Comment by jmorrell** [comment]
We've actually stopped using semver.io in all official buildpacks, and it's not really being actively maintained beyond security updates.

I'm happy to merge a PR, but would you be interested in taking back ownership?

cc @hunterloftis

**Comment by zeke** [comment]
I kinda thought that might be the case. Are you using another service now instead? Solving the range resolution problem a different way?

**Comment by zeke** [comment]
> would you be interested in taking back ownership?

Unfortunately, no. I don't have enough of a need for it right now to take that on.

**Comment by jmorrell** [comment]
> Are you using another service now instead? 

We're using a new service: https://nodebin.herokai.com/ that replaces s3pository and semver.io but is not open source

**Comment by zeke** [comment]
Cool. Is the outside world (e.g. the @probot org) welcome to use this service?

**Comment by jmorrell** [comment]
Ideally not. Currently it only serves Node binaries, but this is likely to be extended in the near future to do things like:

- Support other language runtimes, specifically compiled for Heroku's stack images
- Run integration tests specific to the Heroku platform before binaries are made available
- tag certain releases as "skip" if users experience issues with them on Heroku (ex: Yarn 1.0.0, npm 5.3.0)
- etc

While any iterations will be versioned, we're not really intending for the service to be consumed by third-parties.

What is the use-case for @probot? Is it met by semver.io?

**Comment by zeke** [comment]
Okay thanks for the clarification. semver.io was a longshot solution for  https://github.com/probot/friction/issues/29

**Comment by jmorrell** [comment]
Even with no buildpacks using it, semver.io is still receiving ~80k requests / day during the week which is why we haven't taken it down. Ideally we could pass it off to community owners somehow.

**Comment by zeke** [comment]
> semver.io is still receiving ~80k requests / day

That warms my heart :)

**Comment by zeke** [comment]
Maybe we could start a fund for it with OpenCollective or something. Any idea who's using it? Forked buildpacks mostly?
