### ISSUE TITLE
Yarn Versions Sometimes Fail to Load

### ISSUE THREAD

**Issue by EndangeredMassa** [heroku/semver.io#68]
Sometimes this route will load the data I expect, but sometimes it will not. Refreshing the browser seems to randomly provide valid or invalid responses. This happens for Yarn and NPM, but not the others, as far as I can tell.

https://semver.io/yarn.json

https://semver.io/npm.json

```
{"all":[],"stableVersions":[]}
```

```
{"stable":"1.16.0","unstable":"1.16.0","all":["0.1.0","0.1.1","0.1.2","0.1.3","0.15.1","0.16.0","0.16.1","0.17.0","0.17.2","0.17.3","0.17.4","0.17.5","0.17.6","0.17.7","0.17.8","0.17.9","0.17.10","0.18.0","0.18.1","0.18.2","0.19.0","0.19.1","0.20.0","0.20.3","0.20.4","0.21.0","0.21.1","0.21.2","0.21.3","0.22.0","0.23.0","0.23.1","0.23.2","0.23.3","0.23.4","0.24.0","0.24.1","0.24.2","0.24.3","0.24.4","0.24.5","0.24.6","0.25.1","0.25.2","0.25.3","0.25.4","0.26.0","0.26.1","0.27.0","0.27.1","0.27.2","0.27.3","0.27.4","0.27.5","0.28.1","0.28.4","1.0.0","1.0.1","1.0.2","1.1.0","1.2.0","1.2.1","1.3.1","1.3.2","1.4.0","1.5.0","1.5.1","1.6.0","1.7.0","1.8.0","1.9.1","1.9.2","1.9.4","1.10.0","1.10.1","1.11.0","1.11.1","1.12.0","1.12.1","1.12.3","1.13.0","1.14.0","1.15.0","1.15.1","1.15.2","1.16.0"],"stableVersions":["0.1.0","0.1.1","0.1.2","0.1.3","0.15.1","0.16.0","0.16.1","0.17.0","0.17.2","0.17.3","0.17.4","0.17.5","0.17.6","0.17.7","0.17.8","0.17.9","0.17.10","0.18.0","0.18.1","0.18.2","0.19.0","0.19.1","0.20.0","0.20.3","0.20.4","0.21.0","0.21.1","0.21.2","0.21.3","0.22.0","0.23.0","0.23.1","0.23.2","0.23.3","0.23.4","0.24.0","0.24.1","0.24.2","0.24.3","0.24.4","0.24.5","0.24.6","0.25.1","0.25.2","0.25.3","0.25.4","0.26.0","0.26.1","0.27.0","0.27.1","0.27.2","0.27.3","0.27.4","0.27.5","0.28.1","0.28.4","1.0.0","1.0.1","1.0.2","1.1.0","1.2.0","1.2.1","1.3.1","1.3.2","1.4.0","1.5.0","1.5.1","1.6.0","1.7.0","1.8.0","1.9.1","1.9.2","1.9.4","1.10.0","1.10.1","1.11.0","1.11.1","1.12.0","1.12.1","1.12.3","1.13.0","1.14.0","1.15.0","1.15.1","1.15.2","1.16.0"],"updated":"2019-06-06T16:07:40.066Z"}
```

This was causing our CI builds to fail.

**Comment by arnaudbesnier** [comment]
Looks like the source of information is not accessible anymore:
```
curl https://skimdb.npmjs.com/
curl: (7) Failed to connect to skimdb.npmjs.com port 443: Connection refused
```

**Comment by arnaudbesnier** [comment]
To bypass the issue, you need to specify the `yarn` version in your `package.json`:
<img width="177" alt="Screenshot 2019-06-07 at 10 33 16" src="https://user-images.githubusercontent.com/664261/59091632-06518a80-8910-11e9-9b65-6be428a07610.png">

**Comment by zeke** [comment]
I don't think this service is actively maintained any more. The Heroku team now uses another service for resolving versions, but I forget what it's called... perhaps @jmorrell can point you in the right direction.

**Comment by lares83** [comment]
NPM suggests to use `replicate.npmjs.com ` instead of `skimdb.npmjs.com` so we should switch to this version

**Comment by jmorrell** [comment]
> The Heroku team now uses another service for resolving versions, but I forget what it's called...

We've now moved this logic into a binary in the buildpack itself to avoid relying on an external service

**Comment by zeke** [comment]
> a binary in the buildpack itself

How does this binary know about all the Node.js versions? Do you have some automation in place to keep the binary up to date?

**Comment by jmorrell** [comment]
> How does this binary know about all the Node.js versions? Do you have some automation in place to keep the binary up to date?

Currently it lists the S3 bucket, which has automations for new versions. Eventually there should be a manifest in the buildpack that a bot will open PRs against, but it might be a while before I get around to building those automations

**Comment by zeke** [comment]
https://github.com/heroku/semver.io/pull/69

**Comment by EndangeredMassa** [comment]
I resolved this on my end by updating the buildpack to one that no longer uses semver.io: https://github.com/heroku/heroku-buildpack-ember-cli

**Comment by edmorley** [comment]
This project + the semver.io site which runs it has been deprecated for some time, and due to be switched off soon - so it should no longer be used.
